hints = [
    "See your achievements with {}achievements",
    "Wondering who's on top? Use {}leaderboard",
    "View your profile with {}profile",
    "View our privacy policy using {}privacy",
    "Are you following our rules? View them with {}rules",
    "Bot lagging? Check my ping using {}ping",
    "Need help? Join our support server with {}support",
    "Are you stuck? View all command information with {}help",
    "Change your typing theme with {}theme premade",
    "Learn more about the monthly season with {}season",
    "Take a typing test with {}tt",
    "Race against others with {}race",
    "Change your typing test language with {}language",
    "Equip one of your badges with {}equip",
    "Learn about the monthly season with {}season",
]
